server:
  port: 8761
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: EUREKA-SERVER
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false