server:
  port: 3000
  servlet:
    context-path: /payment
springdoc:
  swagger-ui:
    enabled: true
    docExpansion: false  
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: PAYMENT-SERVICE
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/payment?nullCatalogMeansCurrent=true&useConfigs=maxPerformance&characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      
management:
  health:
     show-details: always
  endpoint:
    health:
      show-details: always
  ### Spring boot admin
  endpoints:
    web:
      exposure:
        include: "*"
  ### Spring boot admin
  
  ### resilience4j circuitbreaker

resilience4j:
  circuitbreaker:
    instances:
      getPatientInstance:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
   ### resilience4j circuitbreaker

